apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: mta-operator-group
  namespace: openshift-mta
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - openshift-mta
