apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vm-br
spec:
  desiredState:
    interfaces:
    - ipv4:
        dhcp: true
        enabled: true
      ipv6:
        enabled: false
      mac-address: '54:BF:64:6E:91:9F'
      name: enp2s0
      state: up
      type: ethernet    
    - name: vm-br 
      description: |-
        A dedicated OVS bridge with enp2s0 as a port
      type: ovs-bridge
      state: up
      ipv4:
        dhcp: false
        enabled: false        
      ipv6:
        enabled: false  
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: true
        port:
        - name: enp2s0
    ovn:
      bridge-mappings:
      - localnet: vm-br-network
        bridge: vm-br 
        state: present
