apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex-network
  namespace: vm-test01
spec:
  config: '{"name":"br-ex-network","type":"ovn-k8s-cni-overlay","cniVersion":"0.4.0","topology":"localnet","netAttachDefName":"vm-test01/br-ex-network"}'
