{{- if .Values.secrets.createEtcdEncryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hostedcluster.etcdEncryptionKeyName" . }}
  namespace: {{ .Values.cluster.namespace }}
  labels:
    {{- include "hostedcluster.labels" . | nindent 4 }}
type: Opaque
data:
  key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
