apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: sda-lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - deviceSelector:
          paths:
            - /dev/nvme0n1
        name: vg1
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90